schema: 1
libraries:
  VSharp:
    repository: vharris-psp/VSharp
    url: https://github.com/vharris-psp/VSharp.git
    path: libs/VSharp
    upstream_branch: main
    work_branch: cucm
    base_commit: ab67228d8671ffa6e968c2fb09d8bbe8d211578e
    version: 0.3.0
  VTModuleSDK:
    repository: vharris-psp/VTModuleSDK
    url: https://github.com/vharris-psp/VTModuleSDK.git
    path: libs/VTModuleSDK
    upstream_branch: main
    work_branch: cucm
    base_commit: 59065739613ac41c4ba662f427b33baa0c075506
    version: 0.5.1
...
