schema: 1
libraries:
  VSharp:
    repository: vharris-psp/VSharp
    url: https://github.com/vharris-psp/VSharp.git
    path: libs/VSharp
    upstream_branch: main
    work_branch: vt/cucm
    base_commit: 7bdb249a77735492d77fd9beae60062f67f742e8
    version: 1.4.3
  VTModuleSDK:
    repository: vharris-psp/VTModuleSDK
    url: https://github.com/vharris-psp/VTModuleSDK.git
    path: libs/VTModuleSDK
    upstream_branch: main
    work_branch: vt/cucm
    base_commit: 96479a053c87cf66845e13cfd1108e76f18070c5
    version: 1.4.2
...
