project: CUCM
schema: vt-project/v1
type: module
environments: {dev: {role: development, mode: dotnet, targets: {run: {command: [], runner: module-source}}}}
app_project: cucm.csproj
kind: module
sign:
  name: CUCM
  project: cucm.csproj
  entitlements: .vt/config/module-entitlements.plist
  output: executable
  mode: onefile
  runtime_identifier: osx-arm64
  input_directory: artifacts/sign/macos/input
  output_directory: artifacts/sign/macos/output
  workflow_artifact: vt-module-cucm-osx-arm64-unsigned
  artifacts:
  - name: vt-module-cucm-osx-arm64
    input: osx-arm64/vt-module-cucm
    output: osx-arm64/vt-module-cucm
    release_asset: vt-module-cucm-osx-arm64
    entitlements: .vt/config/module-entitlements.plist
  identity: 'Developer ID Application: Petoskey Public Schools (8BP6XWVQT9)'
  package_identifier: org.vtools.cucm
...
